include ../../config

INCLUDES +=  -I$(LIBS_ROOT_DIR)/include_ext -I../utls -I../matutls -I../lapack

ransac_CFILES  = Ftools.c Htools.c ranF.c ranH.c rtools.c utools.c experF.c proF.c waldtools.c

LIBS = ransac

$(do_libs)
